// Central item catalogs for Arena Legends
// Silahlar ve zırhlar buradan yönetilir; istediğin zaman isim/dmg/buffları buradan değiştirebilirsin.

const WEAPONS = [
  // --- COMMON WEAPONS ---
  {
    key: 'rusty_sword',
    name: 'Rusty Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'training_spear',
    name: 'Training Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 4,
    max: 7,
    stat: 'Damage',
    price: 8,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'old_mace',
    name: 'Old Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 5,
    max: 8,
    stat: 'Damage',
    price: 10,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- UNCOMMON WEAPONS ---
  {
    key: 'iron_axe',
    name: 'Iron Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 7,
    max: 11,
    stat: 'Damage',
    price: 40,
    minShopLevel: 2,
    statMods: { str: 2 }
  },
  {
    key: 'hunter_bow',
    name: "Hunter's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 45,
    minShopLevel: 2,
    statMods: { chr: 1 }
  },
  {
    key: 'steel_dagger',
    name: 'Steel Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 38,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },

  // --- RARE WEAPONS ---
  {
    key: 'soldier_blade',
    name: "Soldier's Blade",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 90,
    minShopLevel: 3,
    statMods: { atk: 2 }
  },
  {
    key: 'warhammer_of_dawn',
    name: 'Warhammer of Dawn',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 3, def: 1 }
  },
  {
    key: 'spear_of_the_wind',
    name: 'Spear of the Wind',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 16,
    stat: 'Damage',
    price: 100,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },

  // --- EPIC WEAPONS ---
  {
    key: 'shadowfang',
    name: 'Shadowfang',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 180,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'stormreaver',
    name: 'Stormreaver Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'arcanists_staff',
    name: "Arcanist's Staff",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 190,
    minShopLevel: 4,
    statMods: { mag: 4, atk: 1 }
  },

  // --- LEGENDARY WEAPONS ---
  {
    key: 'the_eclipse',
    name: 'The Eclipse',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 5,
    statMods: { str: 7, atk: 12 }
  },
  {
    key: 'dragonspine_bow',
    name: 'Dragonspine Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 16,
    max: 24,
    stat: 'Damage',
    price: 390,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 3 }
  },
  {
    key: 'earthshaker',
    name: 'Earthshaker Maul',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 20,
    max: 30,
    stat: 'Damage',
    price: 420,
    minShopLevel: 6,
    statMods: { str: 6, def: 3, vit: 2 }
  }
];

const ARMORS = [
  // --- COMMON ARMOR ---
  {
    key: 'leather_helm',
    name: 'Leather Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'head',
    baseType: 'Helm',
    val: 3,
    stat: 'Armor',
    price: 25,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'leather_boots',
    name: 'Leather Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Greaves',
    val: 3,
    stat: 'Armor',
    price: 20,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'padded_vest',
    name: 'Padded Vest',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 4,
    stat: 'Armor',
    price: 30,
    minShopLevel: 1,
    statMods: {}
  },

  // --- UNCOMMON ARMOR ---
  {
    key: 'iron_chest',
    name: 'Iron Chestplate',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 7,
    stat: 'Armor',
    price: 70,
    minShopLevel: 2,
    statMods: { vit: 1 }
  },
  {
    key: 'iron_gauntlets',
    name: 'Iron Gauntlets',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 5,
    stat: 'Armor',
    price: 55,
    minShopLevel: 2,
    statMods: { atk: 1 }
  },
  {
    key: 'iron_greaves',
    name: 'Iron Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shins',
    baseType: 'Greaves',
    val: 6,
    stat: 'Armor',
    price: 60,
    minShopLevel: 2,
    statMods: { def: 1 }
  },

  // --- RARE ARMOR ---
  {
    key: 'guardian_shield',
    name: 'Guardian Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shield',
    baseType: 'Shield',
    val: 10,
    stat: 'Armor',
    price: 120,
    minShopLevel: 3,
    statMods: { def: 2 }
  },
  {
    key: 'battle_mantle',
    name: 'Battle Mantle',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shoulders',
    baseType: 'Pauldrons',
    val: 8,
    stat: 'Armor',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 2 }
  },
  {
    key: 'mage_robe',
    name: "Mage's Robe",
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'chest',
    baseType: 'Robe',
    val: 6,
    stat: 'Armor',
    price: 115,
    minShopLevel: 3,
    statMods: { mag: 3 }
  },

  // --- EPIC ARMOR ---
  {
    key: 'oathbound_helm',
    name: 'Oathbound Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'head',
    baseType: 'Helm',
    val: 11,
    stat: 'Armor',
    price: 200,
    minShopLevel: 4,
    statMods: { vit: 2, def: 1 }
  },
  {
    key: 'stormplate',
    name: 'Stormplate Armor',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Breastplate',
    val: 14,
    stat: 'Armor',
    price: 230,
    minShopLevel: 4,
    statMods: { vit: 2, str: 1 }
  },
  {
    key: 'veilwalkers_boots',
    name: "Veilwalker's Boots",
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shins',
    baseType: 'Greaves',
    val: 10,
    stat: 'Armor',
    price: 210,
    minShopLevel: 4,
    statMods: { chr: 2, atk: 1 }
  },

  // --- LEGENDARY ARMOR ---
  {
    key: 'dragon_greaves',
    name: 'Dragon Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shins',
    baseType: 'Greaves',
    val: 15,
    stat: 'Armor',
    price: 350,
    minShopLevel: 5,
    statMods: { vit: 2 }
  },
  {
    key: 'aegis_of_kings',
    name: 'Aegis of Kings',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shield',
    baseType: 'Shield',
    val: 18,
    stat: 'Armor',
    price: 420,
    minShopLevel: 6,
    statMods: { def: 4, vit: 2 }
  },
  {
    key: 'crown_of_the_void',
    name: 'Crown of the Void',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'head',
    baseType: 'Crown',
    val: 12,
    stat: 'Armor',
    price: 380,
    minShopLevel: 6,
    statMods: { mag: 4, chr: 3 }
  }
];
