// Central item catalogs for Arena Legends
// Silahlar ve zırhlar buradan yönetilir; istediğin zaman isim/dmg/buffları buradan değiştirebilirsin.

const WEAPONS = [
  // --- COMMON WEAPONS ---
  {
    key: 'rusty_sword',
    name: 'Rusty Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'training_spear',
    name: 'Training Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 4,
    max: 7,
    stat: 'Damage',
    price: 8,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'old_mace',
    name: 'Old Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 5,
    max: 8,
    stat: 'Damage',
    price: 10,
    minShopLevel: 1,
    statMods: { def: 1 }
  },
  {
    key: 'chipped_dagger',
    name: 'Chipped Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 2,
    max: 5,
    stat: 'Damage',
    price: 6,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'worn_shortbow',
    name: 'Worn Shortbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 3,
    max: 7,
    stat: 'Damage',
    price: 9,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'splintered_staff',
    name: 'Splintered Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 7,
    minShopLevel: 1,
    statMods: { mag: 1 }
  },
  {
    key: 'crude_handaxe',
    name: 'Crude Handaxe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Hand Axe',
    weaponClass: 'Axe',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 11,
    minShopLevel: 1,
    statMods: { str: 1 }
  },
  {
    key: 'militia_sword',
    name: 'Militia Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Shortsword',
    weaponClass: 'Sword',
    min: 4,
    max: 8,
    stat: 'Damage',
    price: 12,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'practice_club',
    name: 'Practice Club',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Club',
    weaponClass: 'Hammer',
    min: 3,
    max: 6,
    stat: 'Damage',
    price: 5,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'guard_spear',
    name: 'Guard Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'common',
    rarity: 'rarity-common',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 14,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- UNCOMMON WEAPONS ---
  {
    key: 'iron_axe',
    name: 'Iron Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 7,
    max: 11,
    stat: 'Damage',
    price: 40,
    minShopLevel: 2,
    statMods: { str: 2 }
  },
  {
    key: 'hunter_bow',
    name: "Hunter's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 45,
    minShopLevel: 2,
    statMods: { chr: 1 }
  },
  {
    key: 'steel_dagger',
    name: 'Steel Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 5,
    max: 9,
    stat: 'Damage',
    price: 38,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'tempered_sword',
    name: 'Tempered Sword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 50,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'ranger_longbow',
    name: 'Ranger Longbow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Longbow',
    weaponClass: 'Bow',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 55,
    minShopLevel: 2,
    statMods: { chr: 2 }
  },
  {
    key: 'duelist_rapier',
    name: 'Duelist Rapier',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Rapier',
    weaponClass: 'Sword',
    min: 6,
    max: 11,
    stat: 'Damage',
    price: 48,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'reinforced_mace',
    name: 'Reinforced Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 8,
    max: 13,
    stat: 'Damage',
    price: 52,
    minShopLevel: 2,
    statMods: { str: 2 }
  },
  {
    key: 'skirmisher_spear',
    name: 'Skirmisher Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 7,
    max: 12,
    stat: 'Damage',
    price: 46,
    minShopLevel: 2,
    statMods: { atk: 1, def: 1 }
  },
  {
    key: 'twinfang_knives',
    name: 'Twinfang Knives',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Knives',
    weaponClass: 'Dagger',
    min: 6,
    max: 10,
    stat: 'Damage',
    price: 44,
    minShopLevel: 2,
    statMods: { atk: 2 }
  },
  {
    key: 'bonecrusher_flail',
    name: 'Bonecrusher Flail',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    baseType: 'Flail',
    weaponClass: 'Hammer',
    min: 8,
    max: 14,
    stat: 'Damage',
    price: 58,
    minShopLevel: 2,
    statMods: { str: 1, vit: 1 }
  },

  // --- RARE WEAPONS ---
  {
    key: 'soldier_blade',
    name: "Soldier's Blade",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 90,
    minShopLevel: 3,
    statMods: { atk: 2 }
  },
  {
    key: 'warhammer_of_dawn',
    name: 'Warhammer of Dawn',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 3, def: 1 }
  },
  {
    key: 'spear_of_the_wind',
    name: 'Spear of the Wind',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 16,
    stat: 'Damage',
    price: 100,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },
  {
    key: 'nightwarden_blade',
    name: 'Nightwarden Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Sword',
    weaponClass: 'Sword',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 120,
    minShopLevel: 3,
    statMods: { atk: 2, def: 1 }
  },
  {
    key: 'thunderstrike_mace',
    name: 'Thunderstrike Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 3 }
  },
  {
    key: 'dragonspear',
    name: 'Dragonspear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 11,
    max: 17,
    stat: 'Damage',
    price: 125,
    minShopLevel: 3,
    statMods: { str: 2, atk: 1 }
  },
  {
    key: 'moonlit_bow',
    name: 'Moonlit Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 10,
    max: 16,
    stat: 'Damage',
    price: 115,
    minShopLevel: 3,
    statMods: { chr: 2, atk: 1 }
  },
  {
    key: 'champion_greatsword',
    name: 'Champion Greatsword',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 135,
    minShopLevel: 3,
    statMods: { str: 3, vit: 1 }
  },
  {
    key: 'runed_halberd',
    name: 'Runed Halberd',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Halberd',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 2, mag: 1 }
  },
  {
    key: 'soulpiercer_dagger',
    name: 'Soulpiercer Dagger',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 10,
    max: 15,
    stat: 'Damage',
    price: 118,
    minShopLevel: 3,
    statMods: { atk: 2, chr: 1 }
  },

  // --- EPIC WEAPONS ---
  {
    key: 'shadowfang',
    name: 'Shadowfang',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 180,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'stormreaver',
    name: 'Stormreaver Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'arcanists_staff',
    name: "Arcanist's Staff",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 12,
    max: 18,
    stat: 'Damage',
    price: 190,
    minShopLevel: 4,
    statMods: { mag: 4, atk: 1 }
  },
  {
    key: 'bloodsong_saber',
    name: 'Bloodsong Saber',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Saber',
    weaponClass: 'Sword',
    min: 14,
    max: 21,
    stat: 'Damage',
    price: 210,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 1 }
  },
  {
    key: 'voidpiercer_spear',
    name: 'Voidpiercer Spear',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Spear',
    weaponClass: 'Spear',
    min: 13,
    max: 20,
    stat: 'Damage',
    price: 205,
    minShopLevel: 4,
    statMods: { atk: 3, mag: 1 }
  },
  {
    key: 'stormcallers_bow',
    name: "Stormcaller's Bow",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 14,
    max: 22,
    stat: 'Damage',
    price: 215,
    minShopLevel: 4,
    statMods: { atk: 2, chr: 3 }
  },
  {
    key: 'emberheart_mace',
    name: 'Emberheart Mace',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Mace',
    weaponClass: 'Hammer',
    min: 15,
    max: 22,
    stat: 'Damage',
    price: 220,
    minShopLevel: 4,
    statMods: { str: 4, vit: 1 }
  },
  {
    key: 'kingslayer_axe',
    name: 'Kingslayer Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 16,
    max: 23,
    stat: 'Damage',
    price: 225,
    minShopLevel: 4,
    statMods: { str: 3, atk: 2 }
  },
  {
    key: 'ghostwalk_daggers',
    name: 'Ghostwalk Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 13,
    max: 19,
    stat: 'Damage',
    price: 200,
    minShopLevel: 4,
    statMods: { atk: 3, chr: 2 }
  },
  {
    key: 'astral_staff',
    name: 'Astral Staff',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    baseType: 'Staff',
    weaponClass: 'Spear',
    min: 12,
    max: 19,
    stat: 'Damage',
    price: 205,
    minShopLevel: 4,
    statMods: { mag: 5 }
  },

  // --- LEGENDARY WEAPONS ---
  {
    key: 'the_eclipse',
    name: 'The Eclipse',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Greatsword',
    weaponClass: 'Sword',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 5,
    statMods: { str: 7, atk: 12 },
    info: "'They won't even notice...'",
    infoColor: 'text-purple'
  },
  {
    key: 'dragonspine_bow',
    name: 'Dragonspine Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 16,
    max: 24,
    stat: 'Damage',
    price: 390,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 3 }
  },
  {
    key: 'earthshaker',
    name: 'Earthshaker Maul',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Hammer',
    weaponClass: 'Hammer',
    min: 20,
    max: 30,
    stat: 'Damage',
    price: 420,
    minShopLevel: 6,
    statMods: { str: 6, def: 3, vit: 2 },
  },
  {
    key: 'sunbreaker_lance',
    name: 'Sunbreaker Lance',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Lance',
    weaponClass: 'Spear',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 410,
    minShopLevel: 6,
    statMods: { str: 5, atk: 4 },
    info: "'Like my weapon?'",
    infoColor: 'text-purple'
  },
  {
    key: 'voidreaver_blade',
    name: 'Voidreaver Blade',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Blade',
    weaponClass: 'Sword',
    min: 20,
    max: 28,
    stat: 'Damage',
    price: 430,
    minShopLevel: 6,
    statMods: { atk: 8, mag: 4 }
  },
  {
    key: 'phoenix_talon',
    name: 'Phoenix Talon',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Dagger',
    weaponClass: 'Dagger',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 400,
    minShopLevel: 5,
    statMods: { atk: 6, chr: 4 }
  },
  {
    key: 'worldsplitter_axe',
    name: 'Worldsplitter Axe',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'War Axe',
    weaponClass: 'Axe',
    min: 21,
    max: 30,
    stat: 'Damage',
    price: 440,
    minShopLevel: 6,
    statMods: { str: 7, vit: 3 }
  },
  {
    key: 'crownslayer_daggers',
    name: 'Crownslayer Daggers',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Daggers',
    weaponClass: 'Dagger',
    min: 19,
    max: 27,
    stat: 'Damage',
    price: 415,
    minShopLevel: 6,
    statMods: { atk: 7, chr: 3 }
  },
  {
    key: 'starfall_bow',
    name: 'Starfall Bow',
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Bow',
    weaponClass: 'Bow',
    min: 18,
    max: 26,
    stat: 'Damage',
    price: 405,
    minShopLevel: 5,
    statMods: { atk: 5, chr: 4, mag: 2 }
  },
  {
    key: 'titans_grip_maul',
    name: "Titan's Grip Maul",
    type: 'weapon',
    category: 'weapon',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    baseType: 'Maul',
    weaponClass: 'Hammer',
    min: 22,
    max: 32,
    stat: 'Damage',
    price: 450,
    minShopLevel: 6,
    statMods: { str: 8, def: 4, vit: 3 }
  }
];

const ARMORS = [
  // --- COMMON ARMOR ---
  {
    key: 'leather_helm',
    name: 'Leather Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'head',
    baseType: 'Helm',
    val: 3,
    stat: 'Armor',
    price: 25,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'leather_boots',
    name: 'Leather Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Greaves',
    val: 3,
    stat: 'Armor',
    price: 20,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'padded_vest',
    name: 'Padded Vest',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 4,
    stat: 'Armor',
    price: 30,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'cloth_hood',
    name: 'Cloth Hood',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'head',
    baseType: 'Hood',
    val: 2,
    stat: 'Armor',
    price: 15,
    minShopLevel: 1,
    statMods: { mag: 1 }
  },
  {
    key: 'travelers_cloak',
    name: "Traveler's Cloak",
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shoulders',
    baseType: 'Cloak',
    val: 3,
    stat: 'Armor',
    price: 22,
    minShopLevel: 1,
    statMods: { chr: 1 }
  },
  {
    key: 'worn_bracers',
    name: 'Worn Bracers',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'arms',
    baseType: 'Bracers',
    val: 3,
    stat: 'Armor',
    price: 20,
    minShopLevel: 1,
    statMods: { atk: 1 }
  },
  {
    key: 'stitched_greaves',
    name: 'Stitched Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Greaves',
    val: 4,
    stat: 'Armor',
    price: 28,
    minShopLevel: 1,
    statMods: {}
  },
  {
    key: 'buckler_shield',
    name: 'Buckler Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shield',
    baseType: 'Shield',
    val: 4,
    stat: 'Armor',
    price: 30,
    minShopLevel: 1,
    statMods: { def: 1 }
  },
  {
    key: 'quilted_pants',
    name: 'Quilted Pants',
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'shins',
    baseType: 'Leggings',
    val: 3,
    stat: 'Armor',
    price: 23,
    minShopLevel: 1,
    statMods: { vit: 1 }
  },
  {
    key: 'guards_tunic',
    name: "Guard's Tunic",
    type: 'armor',
    category: 'armor',
    rarityKey: 'common',
    rarity: 'rarity-common',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 4,
    stat: 'Armor',
    price: 32,
    minShopLevel: 1,
    statMods: { def: 1 }
  },

  // --- UNCOMMON ARMOR ---
  {
    key: 'iron_chest',
    name: 'Iron Chestplate',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'chest',
    baseType: 'Chestplate',
    val: 7,
    stat: 'Armor',
    price: 70,
    minShopLevel: 2,
    statMods: { vit: 1 }
  },
  {
    key: 'iron_gauntlets',
    name: 'Iron Gauntlets',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 5,
    stat: 'Armor',
    price: 55,
    minShopLevel: 2,
    statMods: { atk: 1 }
  },
  {
    key: 'iron_greaves',
    name: 'Iron Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shins',
    baseType: 'Greaves',
    val: 6,
    stat: 'Armor',
    price: 60,
    minShopLevel: 2,
    statMods: { def: 1 }
  },
  {
    key: 'chain_hood',
    name: 'Chain Hood',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'head',
    baseType: 'Coif',
    val: 6,
    stat: 'Armor',
    price: 70,
    minShopLevel: 2,
    statMods: { def: 1 }
  },
  {
    key: 'chain_boots',
    name: 'Chain Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shins',
    baseType: 'Sabatons',
    val: 6,
    stat: 'Armor',
    price: 72,
    minShopLevel: 2,
    statMods: { vit: 1 }
  },
  {
    key: 'reinforced_bracers',
    name: 'Reinforced Bracers',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'arms',
    baseType: 'Bracers',
    val: 5,
    stat: 'Armor',
    price: 65,
    minShopLevel: 2,
    statMods: { atk: 1, def: 1 }
  },
  {
    key: 'scout_mantle',
    name: 'Scout Mantle',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shoulders',
    baseType: 'Mantle',
    val: 5,
    stat: 'Armor',
    price: 60,
    minShopLevel: 2,
    statMods: { chr: 1, atk: 1 }
  },
  {
    key: 'kite_shield',
    name: 'Kite Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'shield',
    baseType: 'Shield',
    val: 8,
    stat: 'Armor',
    price: 80,
    minShopLevel: 2,
    statMods: { def: 2 }
  },
  {
    key: 'brigand_vest',
    name: 'Brigand Vest',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'chest',
    baseType: 'Vest',
    val: 6,
    stat: 'Armor',
    price: 68,
    minShopLevel: 2,
    statMods: { atk: 1, chr: 1 }
  },
  {
    key: 'sentry_mask',
    name: 'Sentry Mask',
    type: 'armor',
    category: 'armor',
    rarityKey: 'uncommon',
    rarity: 'rarity-uncommon',
    slot: 'head',
    baseType: 'Mask',
    val: 5,
    stat: 'Armor',
    price: 62,
    minShopLevel: 2,
    statMods: { chr: 1, def: 1 }
  },

  // --- RARE ARMOR ---
  {
    key: 'guardian_shield',
    name: 'Guardian Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shield',
    baseType: 'Shield',
    val: 10,
    stat: 'Armor',
    price: 120,
    minShopLevel: 3,
    statMods: { def: 2 }
  },
  {
    key: 'battle_mantle',
    name: 'Battle Mantle',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shoulders',
    baseType: 'Pauldrons',
    val: 8,
    stat: 'Armor',
    price: 110,
    minShopLevel: 3,
    statMods: { str: 2 }
  },
  {
    key: 'mage_robe',
    name: "Mage's Robe",
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'chest',
    baseType: 'Robe',
    val: 6,
    stat: 'Armor',
    price: 115,
    minShopLevel: 3,
    statMods: { mag: 3 }
  },
  {
    key: 'lion_helm',
    name: 'Lion Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'head',
    baseType: 'Helm',
    val: 9,
    stat: 'Armor',
    price: 130,
    minShopLevel: 3,
    statMods: { str: 2, vit: 1 }
  },
  {
    key: 'warlord_cuirass',
    name: 'Warlord Cuirass',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'chest',
    baseType: 'Cuirass',
    val: 11,
    stat: 'Armor',
    price: 145,
    minShopLevel: 3,
    statMods: { vit: 2, def: 1 }
  },
  {
    key: 'spellbinder_gloves',
    name: 'Spellbinder Gloves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'arms',
    baseType: 'Gloves',
    val: 7,
    stat: 'Armor',
    price: 125,
    minShopLevel: 3,
    statMods: { mag: 3 }
  },
  {
    key: 'shadowstep_boots',
    name: 'Shadowstep Boots',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shins',
    baseType: 'Boots',
    val: 8,
    stat: 'Armor',
    price: 130,
    minShopLevel: 3,
    statMods: { atk: 1, chr: 2 }
  },
  {
    key: 'siege_greaves',
    name: 'Siege Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shins',
    baseType: 'Greaves',
    val: 9,
    stat: 'Armor',
    price: 135,
    minShopLevel: 3,
    statMods: { def: 2, vit: 1 }
  },
  {
    key: 'radiant_cape',
    name: 'Radiant Cape',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shoulders',
    baseType: 'Cape',
    val: 8,
    stat: 'Armor',
    price: 128,
    minShopLevel: 3,
    statMods: { chr: 2, mag: 1 }
  },
  {
    key: 'mirror_shield',
    name: 'Mirror Shield',
    type: 'armor',
    category: 'armor',
    rarityKey: 'rare',
    rarity: 'rarity-rare',
    slot: 'shield',
    baseType: 'Shield',
    val: 11,
    stat: 'Armor',
    price: 150,
    minShopLevel: 3,
    statMods: { def: 3 }
  },

  // --- EPIC ARMOR ---
  {
    key: 'oathbound_helm',
    name: 'Oathbound Helm',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'head',
    baseType: 'Helm',
    val: 11,
    stat: 'Armor',
    price: 200,
    minShopLevel: 4,
    statMods: { vit: 2, def: 1 }
  },
  {
    key: 'stormplate',
    name: 'Stormplate Armor',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Breastplate',
    val: 14,
    stat: 'Armor',
    price: 230,
    minShopLevel: 4,
    statMods: { vit: 2, str: 1 }
  },
  {
    key: 'veilwalkers_boots',
    name: "Veilwalker's Boots",
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shins',
    baseType: 'Greaves',
    val: 10,
    stat: 'Armor',
    price: 210,
    minShopLevel: 4,
    statMods: { chr: 2, atk: 1 }
  },
  {
    key: 'dreadlords_visor',
    name: "Dreadlord's Visor",
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'head',
    baseType: 'Helm',
    val: 13,
    stat: 'Armor',
    price: 230,
    minShopLevel: 4,
    statMods: { def: 2, chr: 1 }
  },
  {
    key: 'heartforge_mail',
    name: 'Heartforge Mail',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Mail',
    val: 15,
    stat: 'Armor',
    price: 250,
    minShopLevel: 4,
    statMods: { vit: 3, def: 1 }
  },
  {
    key: 'thunderbound_gauntlets',
    name: 'Thunderbound Gauntlets',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 12,
    stat: 'Armor',
    price: 225,
    minShopLevel: 4,
    statMods: { str: 2, atk: 2 }
  },
  {
    key: 'skystride_greaves',
    name: 'Skystride Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shins',
    baseType: 'Greaves',
    val: 13,
    stat: 'Armor',
    price: 235,
    minShopLevel: 4,
    statMods: { vit: 2, atk: 1 }
  },
  {
    key: 'phoenix_cloak',
    name: 'Phoenix Cloak',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shoulders',
    baseType: 'Cloak',
    val: 12,
    stat: 'Armor',
    price: 220,
    minShopLevel: 4,
    statMods: { mag: 2, chr: 2 }
  },
  {
    key: 'spellweave_robes',
    name: 'Spellweave Robes',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'chest',
    baseType: 'Robe',
    val: 11,
    stat: 'Armor',
    price: 225,
    minShopLevel: 4,
    statMods: { mag: 4 }
  },
  {
    key: 'bulwark_of_twilight',
    name: 'Bulwark of Twilight',
    type: 'armor',
    category: 'armor',
    rarityKey: 'epic',
    rarity: 'rarity-epic',
    slot: 'shield',
    baseType: 'Shield',
    val: 15,
    stat: 'Armor',
    price: 255,
    minShopLevel: 4,
    statMods: { def: 3, vit: 2 }
  },

  // --- LEGENDARY ARMOR ---
  {
    key: 'dragon_greaves',
    name: 'Dragon Greaves',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shins',
    baseType: 'Greaves',
    val: 15,
    stat: 'Armor',
    price: 350,
    minShopLevel: 5,
    statMods: { vit: 2 }
  },
  {
    key: 'aegis_of_kings',
    name: 'Aegis of Kings',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shield',
    baseType: 'Shield',
    val: 18,
    stat: 'Armor',
    price: 420,
    minShopLevel: 6,
    statMods: { def: 4, vit: 2 }
  },
  {
    key: 'crown_of_the_void',
    name: 'Crown of the Void',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'head',
    baseType: 'Crown',
    val: 12,
    stat: 'Armor',
    price: 380,
    minShopLevel: 6,
    statMods: { mag: 4, chr: 3 }
  },
  {
    key: 'starlight_ward',
    name: 'Starlight Ward',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shoulders',
    baseType: 'Mantle',
    val: 14,
    stat: 'Armor',
    price: 360,
    minShopLevel: 5,
    statMods: { mag: 3, chr: 3 }
  },
  {
    key: 'tyrants_carapace',
    name: "Tyrant's Carapace",
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'chest',
    baseType: 'Plate',
    val: 18,
    stat: 'Armor',
    price: 410,
    minShopLevel: 6,
    statMods: { vit: 3, def: 3 }
  },
  {
    key: 'mask_of_the_depths',
    name: 'Mask of the Depths',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'head',
    baseType: 'Mask',
    val: 15,
    stat: 'Armor',
    price: 380,
    minShopLevel: 6,
    statMods: { mag: 4, def: 2 }
  },
  {
    key: 'celestial_sabatons',
    name: 'Celestial Sabatons',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shins',
    baseType: 'Sabatons',
    val: 16,
    stat: 'Armor',
    price: 390,
    minShopLevel: 5,
    statMods: { vit: 3, chr: 2 }
  },
  {
    key: 'mantle_of_eternity',
    name: 'Mantle of Eternity',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shoulders',
    baseType: 'Cape',
    val: 15,
    stat: 'Armor',
    price: 385,
    minShopLevel: 6,
    statMods: { mag: 3, vit: 2 }
  },
  {
    key: 'gauntlets_of_rage',
    name: 'Gauntlets of Rage',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'arms',
    baseType: 'Gauntlets',
    val: 14,
    stat: 'Armor',
    price: 370,
    minShopLevel: 5,
    statMods: { str: 4, atk: 3 }
  },
  {
    key: 'dragonheart_aegis',
    name: 'Dragonheart Aegis',
    type: 'armor',
    category: 'armor',
    rarityKey: 'legendary',
    rarity: 'rarity-legendary',
    slot: 'shield',
    baseType: 'Shield',
    val: 20,
    stat: 'Armor',
    price: 430,
    minShopLevel: 6,
    statMods: { def: 5, vit: 3 }
  }
];
